version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sushi
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always
   
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    

  sushi-backend:
    image: breeze5690/sushi-backend:v1
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - LOG_LEVEL=Debug
      - JWT_SECRET=
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
      - MIGRATE_DB=true 
    # volumes:
    #   - ./static:/app/static
    depends_on:
      - postgres
    restart: always
