version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sushi
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    restart: always
   

    

  sushi-backend:
    image: breeze5690/sushi-backend:v1
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - LOG_LEVEL=Debug
      - JWT_SECRET=secret123
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sushi
      - SSH_HOST=
      - SSH_PORT=22
      - SSH_USER=
      - |
        SSH_PRIVATE_KEY=
      - MIGRATE_DB=false 
    depends_on:
      - postgres
    restart: always
